* Robonona

Robonona is a collection of mattermost integrations which I use at my mattermost-based workplace for cultural reasons

** Installation

1. Install [[https://babashka.org/][Babashka]], a Clojure environment optimized for the CLI, via the package manager of your choice.

** Configuration

*** Slack Coffeebot

The coffeebot pairs users from a Slack channel for coffee chats.

**** Required
- =SLACK_TOKEN= :: Bot/user token for Slack API
- =SLACK_CHANNEL= :: Channel ID to fetch users from

**** Optional
- =MATCH_ALGORITHM= :: Matching algorithm to use (default: =random=)
  - =random= :: Pure random pairing each run
  - =round-robin= :: Tracks history to ensure users meet everyone before repeating
- =HISTORY_FILE= :: Path to EDN file for storing pairing history (required if =MATCH_ALGORITHM=round-robin=)

**** Configuration Rules
- If =MATCH_ALGORITHM=round-robin=, then =HISTORY_FILE= must be set (the program will exit with an error otherwise)
- If =HISTORY_FILE= is set but =MATCH_ALGORITHM=random=, the history file is simply unused

*** Legacy Mattermost

The following environment variables are for legacy Mattermost integrations:

- =ROBONONA_MATTERMOST_URL= :: The hostname of your mattermost instance
- =ROBONONA_MATTERMOST_USER= :: The user that this script will operate as
- =ROBONONA_MATTERMOST_PASSWORD= :: The password for said user
- =ROBONONA_MATTERMOST_CHANNEL= :: The channel this script will use
- =ROBONONA_BIRTHDAY_ICAL_URL= :: The URL for the BambooHR birthday iCalendar
- =ROBONONA_ANNIVERSARY_ICAL_URL= :: The URL for the BambooHR anniversary iCalendar
- =ROBONONA_DRY_RUN= :: Set to 1 to omit sending actual messages to mattermost

** Kubernetes Deployment

A Helm chart is provided in =helm-chart/= for deploying to Kubernetes.

*** Install (Random Matching)
#+BEGIN_SRC bash
helm install coffeebot ./helm-chart \
  --namespace coffeebot --create-namespace \
  --set slackToken="xoxb-your-token" \
  --set slackChannel="C12345678"
#+END_SRC

*** Install (Round-Robin Matching)
#+BEGIN_SRC bash
helm install coffeebot ./helm-chart \
  --namespace coffeebot --create-namespace \
  --set slackToken="xoxb-your-token" \
  --set slackChannel="C12345678" \
  --set matchAlgorithm="round-robin" \
  --set persistence.enabled=true
#+END_SRC

*** Upgrade
#+BEGIN_SRC bash
helm upgrade coffeebot ./helm-chart \
  --namespace coffeebot \
  --set slackToken="xoxb-your-token" \
  --set slackChannel="C12345678"
#+END_SRC

** Usage

*** Print a list of everyone's birthdays and anniversaries
#+BEGIN_SRC bash
bb ./celebrate.clj
#+END_SRC

*** Match people in a particular channel to encourage socialization
#+BEGIN_SRC bash
bb ./coffee.clj
#+END_SRC

** Versioning

This project follows [[https://semver.org/][Semantic Versioning]].

** Contributing
Pull requests are welcome. For major changes, please open an issue first to discuss what you would like to change.

Please make sure to update tests as appropriate.

## License
[[https://choosealicense.com/licenses/epl-1.0/][Eclipse Public License 1.0]]
