---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coffeebot.fullname" . }}
  labels:
    {{- include "coffeebot.labels" . | nindent 4 }}
type: Opaque
stringData:
  slack-token: {{ .Values.slackToken | quote }}
