---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coffeebot.fullname" . }}
  labels:
    {{- include "coffeebot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if eq .Values.chatBackend "slack" }}
  slack-token: {{ .Values.slack.token | quote }}
  {{- end }}
  {{- if eq .Values.chatBackend "mattermost" }}
  mattermost-token: {{ .Values.mattermost.token | quote }}
  {{- end }}
